import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";



export const metadata: Metadata = {
  title: "cherie's blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider></ThemeProvider>
        {children}
      </body>
    </html>
  );
}
